kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'html-openshift-app:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nginx:1.24-ubi9'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/marzonev/M109.git'
    contextDir: /block-6/auftrag-6.2%2B/app
    sourceSecret:
      name: marzonev-repo-access
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: github-webhook
  runPolicy: Serial
