kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: test
  namespace: 254201-zlic-nmarzo1
  uid: 353f0e87-952a-43a6-a71e-298edd8a8595
  resourceVersion: '4804314955'
  creationTimestamp: '2025-06-24T09:38:03Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: autoscaling/v2
      time: '2025-06-24T09:38:03Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:maxReplicas': {}
          'f:metrics': {}
          'f:minReplicas': {}
          'f:scaleTargetRef':
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: autoscaling/v2
      time: '2025-06-24T09:38:33Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"AbleToScale"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"ScalingActive"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"ScalingLimited"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:currentMetrics': {}
          'f:currentReplicas': {}
          'f:desiredReplicas': {}
      subresource: status
spec:
  scaleTargetRef:
    kind: Deployment
    name: html-openshift-app
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
status:
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageValue: '0'
          averageUtilization: 0
    - type: Resource
      resource:
        name: memory
        current:
          averageValue: '11939840'
          averageUtilization: 8
  conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2025-06-24T09:38:18Z'
      reason: ReadyForNewScale
      message: recommended size matches current size
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2025-06-24T09:38:33Z'
      reason: ValidMetricFound
      message: the HPA was able to successfully calculate a replica count from memory resource utilization (percentage of request)
    - type: ScalingLimited
      status: 'False'
      lastTransitionTime: '2025-06-24T09:38:33Z'
      reason: DesiredWithinRange
      message: the desired count is within the acceptable range
