kind: Secret
apiVersion: v1
metadata:
  name: github-webhook
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  WebHookSecretKey: YjQ0MmNjYmEzNGRmMWIxNQ==
type: Opaque
