kind: Service
apiVersion: v1
metadata:
  name: html-openshift-app # Hostname
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080 
      targetPort: 8080
  selector: #Verbindung zum Pod
    app: html-openshift-app